import 'dotenv/config'

import {createReadStream} from 'node:fs'
import {randomUUID} from 'node:crypto'
import {resolve} from 'node:path'

import {createClient} from 'next-sanity'

import {apiVersion, dataset, projectId} from '../src/sanity/env'

/**
 * Seed the Sanity blog: a single brand author (Hommy), four categories, and 24
 * researched roofing articles with auto-generated cover images.
 *
 *   pnpm blog:seed            # full wipe + rebuild (idempotent)
 *
 * Covers are generated by the dynamic OG route (src/app/og/blog/route.tsx):
 * the script fetches /og/blog?t=<title>&c=<category>, then uploads the PNG to
 * Sanity as the post's mainImage. That route must be reachable while seeding,
 * so run `pnpm dev` in another terminal (default base http://localhost:3000) or
 * point OG_BASE_URL at a deployed instance.
 *
 * Requires SANITY_API_DEV_TOKEN (read+write) in .env.
 */

const token = process.env.SANITY_API_DEV_TOKEN
if (!token) {
  console.error('Missing SANITY_API_DEV_TOKEN in .env. Needs a read+write token.')
  process.exit(1)
}

const OG_BASE = (process.env.OG_BASE_URL ?? 'http://localhost:3000').replace(/\/$/, '')

const client = createClient({
  projectId,
  dataset,
  apiVersion,
  token,
  useCdn: false,
  // 'raw' so the wipe sees BOTH published and draft (drafts.*) documents;
  // otherwise a leftover draft can reference a published post and block its
  // deletion with a 409.
  perspective: 'raw',
})

const PUBLIC_DIR = resolve(process.cwd(), 'public')

// ---------------------------------------------------------------------------
// Portable Text helpers
// ---------------------------------------------------------------------------

const key = () => randomUUID().slice(0, 12)

type Span = {_type: 'span'; _key: string; text: string; marks: string[]}

function span(text: string, marks: string[] = []): Span {
  return {_type: 'span', _key: key(), text, marks}
}

function block(style: string, children: Span[], extra: Record<string, unknown> = {}) {
  return {_type: 'block', _key: key(), style, markDefs: [], children, ...extra}
}

const p = (text: string) => block('normal', [span(text)])
const h2 = (text: string) => block('h2', [span(text)])

function bullets(items: string[]) {
  return items.map((item) => block('normal', [span(item)], {listItem: 'bullet', level: 1}))
}

function numbered(items: string[]) {
  return items.map((item) => block('normal', [span(item)], {listItem: 'number', level: 1}))
}

function callout(tone: 'info' | 'tip' | 'warning' | 'success', title: string, content: string) {
  return {_type: 'callout', _key: key(), tone, title, content}
}

function pullQuote(quote: string, attribution = 'The Hommy Team') {
  return {_type: 'pullQuote', _key: key(), quote, attribution}
}

function cta(label: string, href = 'https://hommy.online/get-a-quote', variant: 'primary' | 'secondary' = 'primary') {
  return {
    _type: 'cta',
    _key: key(),
    label,
    variant,
    link: {_type: 'link', linkType: 'external', href, openInNewTab: false},
  }
}

// A normal paragraph that can carry inline links. Each segment is either a plain
// string, an internal link to another post ({text, post}), or an external link
// ({text, href}). Internal links use the schema's link annotation with an
// internalLink reference so the renderer resolves them to /blog/<slug>.
type Seg = string | {text: string; post: string} | {text: string; href: string}

function lp(segments: Seg[]) {
  const markDefs: Record<string, unknown>[] = []
  const children = segments.map((seg) => {
    if (typeof seg === 'string') return span(seg)
    const k = key()
    if ('post' in seg) {
      markDefs.push({
        _type: 'link',
        _key: k,
        linkType: 'internal',
        // weak so creation order does not matter (post A may link post Z before
        // Z exists); the reference still resolves in GROQ/the renderer.
        internalLink: {_type: 'reference', _ref: `post-${seg.post}`, _weak: true},
        openInNewTab: false,
      })
    } else {
      markDefs.push({_type: 'link', _key: k, linkType: 'external', href: seg.href, openInNewTab: true})
    }
    return span(seg.text, [k])
  })
  return {_type: 'block', _key: key(), style: 'normal', markDefs, children}
}

// ---------------------------------------------------------------------------
// Cover image generation (via the /og/blog route) + brand avatar upload
// ---------------------------------------------------------------------------

const assetCache = new Map<string, string>()

async function uploadFromBuffer(filename: string, buf: Buffer, contentType: string): Promise<string> {
  if (assetCache.has(filename)) return assetCache.get(filename)!
  const existing = await client.fetch<string | null>(
    '*[_type == "sanity.imageAsset" && originalFilename == $filename][0]._id',
    {filename},
  )
  if (existing) {
    assetCache.set(filename, existing)
    return existing
  }
  const asset = await client.assets.upload('image', buf, {filename, contentType})
  assetCache.set(filename, asset._id)
  return asset._id
}

async function uploadCover(slug: string, title: string, categoryTitle: string): Promise<string> {
  const url = `${OG_BASE}/og/blog?t=${encodeURIComponent(title)}&c=${encodeURIComponent(categoryTitle)}`
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(
      `Cover generation failed for "${slug}" (${res.status} ${res.statusText}). ` +
        `Is the app running at ${OG_BASE}? Set OG_BASE_URL or run \`pnpm dev\`.`,
    )
  }
  const buf = Buffer.from(await res.arrayBuffer())
  return uploadFromBuffer(`${slug}.png`, buf, 'image/png')
}

async function uploadLogo(relPath: string): Promise<string> {
  const filename = relPath.split('/').pop()!
  if (assetCache.has(filename)) return assetCache.get(filename)!
  const existing = await client.fetch<string | null>(
    '*[_type == "sanity.imageAsset" && originalFilename == $filename][0]._id',
    {filename},
  )
  if (existing) {
    assetCache.set(filename, existing)
    return existing
  }
  const abs = resolve(PUBLIC_DIR, relPath)
  const asset = await client.assets.upload('image', createReadStream(abs), {filename})
  assetCache.set(filename, asset._id)
  return asset._id
}

// ---------------------------------------------------------------------------
// Author + categories
// ---------------------------------------------------------------------------

const AUTHOR_ID = 'author-hommy'

const categories = [
  {
    _id: 'category-storm-damage',
    title: 'Storm & Damage',
    slug: 'storm-damage',
    description: 'What to do when wind, hail, or a hurricane does a number on your roof.',
  },
  {
    _id: 'category-insurance-claims',
    title: 'Insurance & Claims',
    slug: 'insurance-claims',
    description: 'Filing, fighting for, and understanding your roof insurance claim.',
  },
  {
    _id: 'category-repair-vs-replace',
    title: 'Repair vs Replace',
    slug: 'repair-vs-replace',
    description: 'Costs, lifespan, and the call between patching and replacing your roof.',
  },
  {
    _id: 'category-hiring-a-pro',
    title: 'Hiring a Pro',
    slug: 'hiring-a-pro',
    description: 'Find, vet, and pay a roofing contractor you can actually trust.',
  },
]

// ---------------------------------------------------------------------------
// Posts
// ---------------------------------------------------------------------------

type PostSeed = {
  slug: string
  title: string
  eyebrow: string
  excerpt: string
  category: string
  cover: string // category title passed to the OG route
  readTime: number
  featured?: boolean
  daysAgo: number
  body: unknown[]
  related?: string[]
}

const STORM = 'Storm & Damage'
const INSURANCE = 'Insurance & Claims'
const REPAIR = 'Repair vs Replace'
const HIRING = 'Hiring a Pro'

const posts: PostSeed[] = [
  // ===================== STORM & DAMAGE =====================
  {
    slug: 'signs-of-roof-hail-damage',
    title: 'How to Tell if Your Roof Has Hail Damage After a Storm',
    eyebrow: 'STORM',
    excerpt:
      'Hail damage is often invisible from the ground and easy to miss until it leaks. Here is how to spot the real signs safely, without climbing up.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 7,
    daysAgo: 2,
    related: ['what-storm-damage-to-a-roof-looks-like', 'does-homeowners-insurance-cover-hail-damage', 'how-to-document-roof-damage-for-insurance'],
    body: [
      p('Hail is sneaky. A storm can pass in ten minutes and leave your roof looking completely normal from the street, while the protective surface of your shingles has quietly been beaten down. Months later you notice a stain on the ceiling, and by then a cheap fix has become an expensive one.'),
      p('The good news is that you can catch most hail damage early with a careful look, and you do not need to get on the roof to do it. Here is what to check and what real hail damage actually looks like.'),
      h2('Start on the ground, not the roof'),
      p('You should never climb onto a roof after a storm, especially if it is wet. Most of the useful signs are visible from the yard with a pair of binoculars, or by checking the things hail hits at eye level first.'),
      ...bullets([
        'Dented gutters, downspouts, and metal fascia',
        'Dings or splatter marks on your AC unit, mailbox, or grill',
        'Cracked or broken window screens and damaged siding',
        'A pile of shingle granules at the bottom of downspouts',
      ]),
      callout('tip', 'Check the soft metal first', 'Hail leaves clear dents in soft metal like gutters and vents long before the damage on shingles is obvious. If the metal got hit, the shingles almost certainly did too.'),
      h2('What hail damage looks like on shingles'),
      p('Real hail bruising on an asphalt shingle is different from normal wear. It usually shows up as random, round dark spots where the granules have been knocked off, exposing the black asphalt underneath. Press one and it often feels soft, like a bruise on an apple. The pattern is scattered and random, not in neat lines.'),
      p('Be careful not to confuse hail damage with blistering, normal granule loss from age, or factory defects. Those follow patterns or cover broad areas. Hail is random and tied to the date of the storm.'),
      h2('Look inside too'),
      p('From your attic, look for damp insulation, water stains on the underside of the roof deck, or daylight coming through. A fresh leak after a known hail event is strong evidence the roof was compromised.'),
      pullQuote('Caught the week of the storm, hail damage is a clean insurance claim. Caught a year later, it often looks like neglect, and that is when claims get denied.'),
      h2('When to call a professional'),
      lp([
        'If you see dented metal, granules in the gutters, or any interior signs, get a free professional inspection before you assume the roof is fine. A reputable roofer documents the damage properly, which matters a great deal when you ',
        {text: 'file an insurance claim', post: 'how-to-file-a-roof-insurance-claim'},
        '. Just be cautious about the crews that show up uninvited right after a storm, which we cover in our guide on ',
        {text: 'red flags when hiring a roofer', post: 'red-flags-when-hiring-a-roofing-contractor'},
        '.',
      ]),
      cta('Get a free hail damage inspection'),
    ],
  },
  {
    slug: 'what-to-do-after-hurricane-roof-damage',
    title: 'What to Do Immediately After a Hurricane Damages Your Roof',
    eyebrow: 'STORM',
    excerpt:
      'In the hours after a hurricane, a few smart moves protect your home and your claim. Here is the right order of operations, step by step.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 8,
    daysAgo: 6,
    related: ['how-to-document-roof-damage-for-insurance', 'how-long-to-file-roof-insurance-claim', 'find-licensed-roofing-contractor-florida'],
    body: [
      p('After a hurricane, the pressure to act fast is real, and so is the risk of making a costly mistake. Move too slowly and water keeps pouring in. Move too fast and you sign with the wrong crew or miss a step your insurer expects. This is the order that protects both your home and your wallet.'),
      h2('1. Make sure it is safe before anything else'),
      p('Do not go outside until officials say it is safe. Stay far away from downed power lines and standing water, which can hide live electricity. Never climb onto a wet or damaged roof. If you smell gas or the structure looks unstable, leave and call for help.'),
      h2('2. Document the damage before you touch it'),
      lp([
        'Before you move debris or start any cleanup, take photos and video from every angle: the roof from the ground, the yard, the gutters, and any water coming inside. Timestamped images are the backbone of your claim. We walk through exactly how to do this in ',
        {text: 'how to document roof damage for an insurance claim', post: 'how-to-document-roof-damage-for-insurance'},
        '.',
      ]),
      h2('3. Stop the bleeding with temporary repairs'),
      p('Your policy expects you to take reasonable steps to prevent further damage. If water is getting in, a tarp over the damaged area or a bucket under a leak counts. Keep every receipt for tarps, plywood, and supplies, because those costs are often reimbursable.'),
      callout('warning', 'Watch out for storm chasers', 'After a major storm, out-of-town crews flood the area with cash deals and high-pressure pitches. Many collect a deposit and vanish. Insist on a local, licensed, insured contractor with a permanent address and a real track record.'),
      h2('4. Call your insurance company'),
      lp([
        'Report the claim promptly. In Florida, the law gives you a limited window to file, and that window is shorter than it used to be. See ',
        {text: 'how long you have to file a roof insurance claim', post: 'how-long-to-file-roof-insurance-claim'},
        ' so you do not lose your right to a payout by waiting.',
      ]),
      h2('5. Get your own inspection'),
      p('The insurance adjuster works for the insurer. Having an independent inspection from a reputable local roofer gives you a second set of eyes and a documented estimate to compare. If the two assessments disagree, you have grounds to push back.'),
      pullQuote('The homeowners who come out ahead after a hurricane are not the fastest to sign a contract. They are the ones who document carefully and choose their roofer deliberately.'),
      h2('6. Be patient with the timeline'),
      lp([
        'A hurricane claim takes longer than a routine one because adjusters are stretched thin. Knowing ',
        {text: 'how long a roof claim takes to pay out', post: 'how-long-roof-insurance-claim-takes-to-pay'},
        ' helps you plan and spot unreasonable delays.',
      ]),
      cta('Find a licensed local roofer'),
    ],
  },
  {
    slug: 'how-long-to-file-roof-insurance-claim',
    title: 'How Long Do You Have to File a Roof Insurance Claim After a Storm?',
    eyebrow: 'STORM',
    excerpt:
      'Claim deadlines are shorter than most homeowners think, and they differ by state. Here is what the rules look like in Texas and Florida in 2026.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 7,
    daysAgo: 10,
    related: ['how-to-file-a-roof-insurance-claim', 'what-to-do-after-hurricane-roof-damage', 'how-long-roof-insurance-claim-takes-to-pay'],
    body: [
      p('The single most expensive mistake homeowners make after a storm is waiting too long. Roof claim deadlines have tightened in recent years, and missing one can cost you the entire payout no matter how legitimate the damage is. Here is how the clock works, with the current rules in the two states where storms hit hardest.'),
      callout('info', 'This is general information, not legal advice', 'Every policy has its own terms, and laws change. Always read your own policy and confirm current deadlines with your insurer or a licensed professional before you rely on a date.'),
      h2('Two different clocks are running'),
      p('There are usually two deadlines to track, and people confuse them constantly:'),
      ...bullets([
        'The notice deadline: how long you have to tell your insurer a loss happened',
        'The lawsuit deadline (statute of limitations): how long you have to sue if the claim is wrongly denied or underpaid',
      ]),
      p('Your policy also almost always requires you to give "prompt" notice, which insurers interpret strictly. Waiting months can give them grounds to deny even if you are still inside a legal deadline.'),
      h2('Florida: one year to file'),
      lp([
        'Florida law (Statute 627.70132, updated by SB 2-A in late 2022) requires you to give notice of a new or reopened property insurance claim within one year of the date of loss. A supplemental claim, where you discover more damage later, must be filed within 18 months. These windows were cut in half from the old rules, so older advice you find online is out of date. If you are in Florida, also read ',
        {text: 'how to find a licensed roofing contractor in Florida', post: 'find-licensed-roofing-contractor-florida'},
        '.',
      ]),
      h2('Texas: generally two years to sue'),
      p('Texas does not have one single filing statute the way Florida does, but the practical deadline for property damage is the two-year statute of limitations, which generally starts on the date the damage occurred, not the date you noticed it. On top of that, Texas Insurance Code Chapter 542A requires you to send the insurer a pre-suit notice at least 61 days before filing a lawsuit, and that waiting period does not pause the two-year clock. If you wait until the last few months, you can run out of time to do both.'),
      pullQuote('Treat the date of the storm as the start of your clock, not the date you finally climbed up and saw the damage.'),
      h2('The practical rule that protects you'),
      p('Forget the fine print for a moment. The safest approach in any state is the same: report a suspected loss within days, not months. Document everything immediately, get an inspection, and file promptly. The deadlines exist as a backstop, but acting fast is what actually keeps your claim clean.'),
      lp([
        'Once you are ready to file, follow our step-by-step walkthrough in ',
        {text: 'how to file a roof insurance claim', post: 'how-to-file-a-roof-insurance-claim'},
        '.',
      ]),
      cta('Get a documented storm inspection'),
    ],
  },
  {
    slug: 'does-homeowners-insurance-cover-hail-damage',
    title: 'Does Homeowners Insurance Cover Hail Damage to Your Roof?',
    eyebrow: 'STORM',
    excerpt:
      'In most cases yes, but the details around deductibles, roof age, and exclusions decide how much you actually get. Here is the honest breakdown.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 8,
    featured: true,
    daysAgo: 14,
    related: ['actual-cash-value-vs-replacement-cost-roof', 'what-roof-damage-is-not-covered-by-insurance', 'signs-of-roof-hail-damage'],
    body: [
      p('Hail is one of the most common reasons roofs get replaced through insurance, and the short answer is reassuring: a standard homeowners policy usually does cover sudden hail damage. The longer answer is where the money is, because three details decide how much actually lands in your pocket.'),
      h2('Hail is typically a covered peril'),
      p('Most standard policies are written to cover sudden, accidental damage from wind and hail. If a storm beats up your roof, that is exactly the kind of event the policy exists for. The fight is rarely about whether hail is covered. It is about how much the insurer agrees to pay.'),
      h2('Detail 1: your deductible'),
      p('You pay your deductible before the insurer pays a dime. Many policies in hail-prone and hurricane-prone areas carry a separate, percentage-based wind and hail deductible, which can be 1 to 5 percent of your home\'s insured value rather than a flat dollar amount. On a $400,000 home, a 2 percent deductible is $8,000, which can be more than a small repair would cost out of pocket.'),
      callout('warning', 'Check for a separate wind/hail deductible', 'A percentage deductible is easy to miss and much larger than the standard one. Find this number in your policy before you file, so the payout does not surprise you.'),
      h2('Detail 2: actual cash value vs replacement cost'),
      lp([
        'This is the biggest swing factor. A replacement cost policy pays what it costs to put on a new roof, minus your deductible. An actual cash value policy subtracts depreciation for the age and wear of your old roof, which can drastically reduce the check. We break this down fully in ',
        {text: 'actual cash value vs replacement cost for roof claims', post: 'actual-cash-value-vs-replacement-cost-roof'},
        '.',
      ]),
      h2('Detail 3: the age and condition of your roof'),
      p('Insurers increasingly limit coverage on older roofs. Some put roofs past a certain age on an actual cash value schedule, paying only the depreciated value even if the rest of your home is on replacement cost. A roof that was already worn or poorly maintained also gives the insurer room to argue the damage was not purely from the hail.'),
      pullQuote('Hail damage is usually covered. The real questions are your deductible, whether you have replacement cost, and how old your roof is.'),
      h2('What can still get you denied'),
      lp([
        'Cosmetic-only damage on some policies, long-neglected wear blamed on age, and damage reported too late are the usual reasons a hail claim shrinks or gets denied. See ',
        {text: 'what roof damage is not covered by insurance', post: 'what-roof-damage-is-not-covered-by-insurance'},
        ' for the full list.',
      ]),
      cta('Find out if your hail damage is claimable'),
    ],
  },
  {
    slug: 'how-to-document-roof-damage-for-insurance',
    title: 'How to Document Roof Damage for an Insurance Claim',
    eyebrow: 'STORM',
    excerpt:
      'A well-documented claim is the difference between a full payout and a fight. Here is exactly what to capture, and how, without risking your safety.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 6,
    daysAgo: 19,
    related: ['how-to-file-a-roof-insurance-claim', 'how-to-deal-with-roof-insurance-adjuster', 'what-to-do-after-hurricane-roof-damage'],
    body: [
      p('Insurance is a paperwork business. When two homeowners have the same damage, the one with clear, dated, organized evidence almost always gets the better settlement. Documentation is the cheapest leverage you have, and it costs nothing but a little time.'),
      h2('Photograph everything, from far and near'),
      ...bullets([
        'Wide shots of the whole house and roof from the ground, on each side',
        'Close-ups of damaged shingles, dented gutters, and torn flashing',
        'Every interior sign: ceiling stains, wet insulation, drips, and pooling water',
        'Damaged belongings inside, if water got to them',
      ]),
      callout('tip', 'Let the timestamp do the work', 'Modern phones embed the date and location in each photo. Take pictures as soon as it is safe, so the timeline ties the damage directly to the storm. Do not climb the roof for a better shot; ground and attic photos are enough.'),
      h2('Write down the storm details'),
      p('Note the date and time of the storm, and save any local weather reports, hail maps, or news coverage confirming severe weather hit your area that day. This connects your damage to a specific covered event, which is exactly what the adjuster needs to see.'),
      h2('Keep a running file of everything'),
      ...numbered([
        'A copy of your insurance policy and your claim number',
        'Every receipt for tarps, repairs, and emergency supplies',
        'A log of every phone call: date, who you spoke to, and what they said',
        'Any written estimates from contractors',
      ]),
      h2('Get a professional inspection report'),
      lp([
        'Your own photos are powerful, but a written inspection from a licensed roofer carries real weight, because it documents damage you cannot see from the ground and puts a credible estimate on the table. That report becomes your reference point when you ',
        {text: 'deal with the insurance adjuster', post: 'how-to-deal-with-roof-insurance-adjuster'},
        '.',
      ]),
      pullQuote('You cannot over-document a claim. Every photo and receipt you save is one less thing the insurer can dispute later.'),
      lp([
        'With your evidence organized, you are ready to ',
        {text: 'file the claim itself', post: 'how-to-file-a-roof-insurance-claim'},
        '.',
      ]),
      cta('Get a documented inspection report'),
    ],
  },
  {
    slug: 'what-storm-damage-to-a-roof-looks-like',
    title: 'What Storm Damage to a Roof Actually Looks Like',
    eyebrow: 'STORM',
    excerpt:
      'Wind, hail, and debris each leave a different signature. Learn to read them so you know when a storm did real harm and when your roof shrugged it off.',
    category: 'category-storm-damage',
    cover: STORM,
    readTime: 7,
    daysAgo: 24,
    related: ['signs-of-roof-hail-damage', 'roof-repair-vs-replacement', 'does-homeowners-insurance-cover-hail-damage'],
    body: [
      p('Not every storm damages a roof, and not every bit of wear is storm damage. Knowing the difference saves you from both ignoring a real problem and filing a claim that goes nowhere. Each type of storm leaves its own fingerprint.'),
      h2('Wind damage'),
      p('Wind works on the edges first. It lifts and creases shingles, then peels them back or tears them off entirely. Look for shingles that are missing, flapping, curled at the corners, or have a horizontal crease line where they were bent back and slapped down. Wind also loosens the sealant strip that holds shingles flat, so a roof can be compromised even when nothing is obviously gone.'),
      ...bullets([
        'Missing shingles, or bright patches where they used to be',
        'Lifted or creased shingles, especially along ridges and edges',
        'Debris from the roof in your yard or gutters',
        'Lifted or detached flashing around chimneys and vents',
      ]),
      h2('Hail damage'),
      lp([
        'Hail leaves random, round bruises where granules were knocked off, exposing dark asphalt. The spots feel soft, like a bruise. Because it is so easy to miss from the ground, hail deserves its own checklist, which we cover in ',
        {text: 'how to tell if your roof has hail damage', post: 'signs-of-roof-hail-damage'},
        '.',
      ]),
      h2('Debris and impact damage'),
      p('Fallen branches and flying debris cause obvious punctures, cracks, and gouges. Even a limb that has already rolled off can leave a crushed area or a hole that lets water straight in. This kind of damage is usually the most urgent, because the barrier is physically broken.'),
      h2('Water intrusion: the delayed signature'),
      p('Some storm damage shows up days or weeks later as the first sign you notice. Watch for ceiling stains, peeling paint, a musty smell, or sagging drywall. By the time water reaches your ceiling, it has usually been traveling through the structure for a while.'),
      callout('info', 'Subtle does not mean harmless', 'A lifted shingle or a loosened sealant strip looks like nothing, but it is an open door for the next rain. Minor-looking storm damage is still worth a professional look.'),
      pullQuote('Wind attacks the edges, hail bruises the field, debris punches holes, and water tells on all three a few weeks later.'),
      lp([
        'Once you know what you are dealing with, the next question is usually ',
        {text: 'whether to repair or replace', post: 'roof-repair-vs-replacement'},
        '.',
      ]),
      cta('Get a storm damage assessment'),
    ],
  },

  // ===================== INSURANCE & CLAIMS =====================
  {
    slug: 'how-to-file-a-roof-insurance-claim',
    title: 'How to File a Roof Insurance Claim, Step by Step',
    eyebrow: 'INSURANCE',
    excerpt:
      'Filing a roof claim is simple if you do it in the right order. Here is the full process from the moment of damage to the final payment.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 9,
    featured: true,
    daysAgo: 4,
    related: ['how-to-document-roof-damage-for-insurance', 'how-to-deal-with-roof-insurance-adjuster', 'how-long-roof-insurance-claim-takes-to-pay'],
    body: [
      p('A roof claim feels intimidating the first time, but it follows a predictable path. Do the steps in order, keep good records, and you remove almost every reason an insurer might delay or shortchange you. Here is the whole process.'),
      h2('Step 1: Confirm the damage is worth a claim'),
      lp([
        'Before you file, get a clear picture of the damage and roughly what it will cost to fix. If the repair is close to or below your deductible, a claim may not be worth it, because every filed claim stays on your record. Check ',
        {text: 'whether filing could affect your renewal', post: 'will-insurance-drop-me-for-roof-claim'},
        ' before you decide.',
      ]),
      h2('Step 2: Document everything first'),
      lp([
        'Photos, video, weather records, and a professional inspection should all be gathered before you call. Our full checklist is in ',
        {text: 'how to document roof damage for an insurance claim', post: 'how-to-document-roof-damage-for-insurance'},
        '.',
      ]),
      h2('Step 3: Review your own policy'),
      p('Pull out your policy and find three things: your deductible (especially any separate wind or hail deductible), whether you have replacement cost or actual cash value coverage, and the notice deadline. Knowing these before you call means no surprises later.'),
      h2('Step 4: File promptly'),
      lp([
        'Report the claim to your insurer as soon as it is safe, by phone or app. Give them the date of loss, a description, and your documentation. Filing quickly matters, because deadlines have tightened. See ',
        {text: 'how long you have to file a claim', post: 'how-long-to-file-roof-insurance-claim'},
        '.',
      ]),
      h2('Step 5: Prevent further damage'),
      p('Tarp leaks and make reasonable temporary repairs to stop additional damage, and keep the receipts. Your policy requires this, and the costs are usually reimbursable. Do not start permanent repairs until the adjuster has seen the roof.'),
      h2('Step 6: Meet the adjuster prepared'),
      lp([
        'The insurer sends an adjuster to inspect. Have your documentation and your independent contractor estimate ready, and ideally have your roofer present. We cover how to handle this meeting in ',
        {text: 'how to deal with an insurance adjuster', post: 'how-to-deal-with-roof-insurance-adjuster'},
        '.',
      ]),
      h2('Step 7: Review the settlement, then recover depreciation'),
      lp([
        'Read the settlement carefully against your contractor\'s estimate. With replacement cost coverage, the first check is often the depreciated amount, and you recover the rest after the work is done and invoiced. Understand this in ',
        {text: 'actual cash value vs replacement cost', post: 'actual-cash-value-vs-replacement-cost-roof'},
        '.',
      ]),
      callout('tip', 'Pay the contractor, not the storm chaser', 'Use a licensed local roofer you chose, not a crew that knocked on your door offering to "handle the whole claim." A legitimate roofer works with your adjuster, not around them.'),
      pullQuote('A roof claim is not won by arguing. It is won by being the most prepared and organized person in the conversation.'),
      cta('Get an inspection before you file'),
    ],
  },
  {
    slug: 'will-insurance-drop-me-for-roof-claim',
    title: 'Will My Insurance Company Drop Me if I File a Roof Claim?',
    eyebrow: 'INSURANCE',
    excerpt:
      'The honest answer: one storm claim rarely gets you dropped, but the pattern matters. Here is how insurers actually decide.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 7,
    daysAgo: 12,
    related: ['how-to-file-a-roof-insurance-claim', 'does-homeowners-insurance-cover-hail-damage', 'what-roof-damage-is-not-covered-by-insurance'],
    body: [
      p('This fear keeps a lot of people from filing claims they are fully entitled to. The reality is more nuanced than "file a claim and lose your policy." Insurers look at patterns, causes, and risk, not a single legitimate storm claim in isolation.'),
      h2('How insurers see your history'),
      p('Almost every insurer checks a database called CLUE (Comprehensive Loss Underwriting Exchange), run by LexisNexis. It records your claims for about seven years, and your insurer pulls it at every renewal. That is why a claim can affect your rate or eligibility long after it is paid.'),
      h2('A single storm claim is usually fine'),
      p('If your claim is clearly for sudden storm damage, verified by inspection, you are using the policy exactly as intended. The impact on your individual standing is often small, and weather claims like wind and hail generally carry less weight than other types. Insurers expect storm claims in storm-prone regions.'),
      callout('info', 'Cause matters more than count', 'A claim from neglect or slow leaks signals ongoing risk and is far more likely to raise your rate or threaten renewal than a one-time storm event.'),
      h2('When the risk of non-renewal goes up'),
      ...bullets([
        'Two or more claims within a short window, typically three to five years',
        'Claims tied to neglect, poor maintenance, or an old worn roof',
        'Water damage and liability claims, which insurers weigh heavily',
        'An aging roof the insurer already considers high risk',
      ]),
      h2('The math before you file'),
      lp([
        'For damage near your deductible, weigh the payout against the long-term cost of having a claim on record. For major storm damage well above your deductible, the calculation usually favors filing. Knowing ',
        {text: 'what is and is not covered', post: 'what-roof-damage-is-not-covered-by-insurance'},
        ' helps you decide whether a claim will even succeed.',
      ]),
      pullQuote('One honest storm claim is rarely the problem. A pattern of claims, or damage that looks like neglect, is what makes insurers nervous.'),
      h2('Protect your standing either way'),
      p('Keep your roof maintained, document its condition, and only file for genuine, sudden damage. A well-kept roof with a clean history is exactly the kind of risk insurers want to keep.'),
      cta('Get an honest damage assessment'),
    ],
  },
  {
    slug: 'how-long-roof-insurance-claim-takes-to-pay',
    title: 'How Long a Roof Insurance Claim Takes to Pay Out',
    eyebrow: 'INSURANCE',
    excerpt:
      'From filing to final check, most roof claims resolve in weeks, not days. Here is a realistic timeline and what can speed it up or slow it down.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 6,
    daysAgo: 17,
    related: ['how-to-file-a-roof-insurance-claim', 'actual-cash-value-vs-replacement-cost-roof', 'how-to-deal-with-roof-insurance-adjuster'],
    body: [
      p('Once you file, the waiting begins, and not knowing what is normal makes it worse. Most roof claims move through a few predictable stages. Here is what the timeline usually looks like and where the delays come from.'),
      h2('The typical stages'),
      ...numbered([
        'You file and receive a claim number, usually within a day or two',
        'An adjuster is assigned and schedules an inspection, often within one to two weeks',
        'The adjuster inspects and writes an estimate',
        'The insurer issues a settlement decision and the first payment',
        'After repairs, you recover any held-back depreciation',
      ]),
      h2('A realistic timeframe'),
      p('A straightforward claim often resolves in two to six weeks from filing to first payment. Complex claims, disputes, or major regional storms that overwhelm adjusters can stretch that to a few months. After a hurricane, expect the longer end, because every adjuster in the area is buried.'),
      callout('info', 'Florida has a hard deadline for insurers', 'Under Florida law, insurers generally must pay or deny a claim within 60 days of receiving notice, and late payments can accrue interest. Other states have their own prompt-payment rules. If your insurer blows past the legal window, that is leverage.'),
      h2('Why the payment often comes in two parts'),
      lp([
        'With replacement cost coverage, the first check is frequently the actual cash value, the depreciated amount, and the rest, the recoverable depreciation, is released after you complete the work and submit the final invoice. This surprises a lot of homeowners. We explain it in ',
        {text: 'actual cash value vs replacement cost', post: 'actual-cash-value-vs-replacement-cost-roof'},
        '.',
      ]),
      h2('What speeds things up'),
      ...bullets([
        'Filing quickly with complete documentation',
        'Having an independent contractor estimate ready before the adjuster visits',
        'Responding to every request from the insurer the same day',
        'Following up in writing and keeping a log of all contact',
      ]),
      pullQuote('Most delays are not the insurer stalling. They are waiting on a document, a signature, or a callback from you.'),
      cta('Get an estimate ready for your adjuster'),
    ],
  },
  {
    slug: 'actual-cash-value-vs-replacement-cost-roof',
    title: 'Actual Cash Value vs Replacement Cost for Roof Claims',
    eyebrow: 'INSURANCE',
    excerpt:
      'These two little terms decide thousands of dollars on your roof claim. Here is what each one pays, with plain-English examples.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 7,
    daysAgo: 22,
    related: ['does-homeowners-insurance-cover-hail-damage', 'how-to-file-a-roof-insurance-claim', 'how-long-roof-insurance-claim-takes-to-pay'],
    body: [
      p('If you read one thing about roof insurance, make it this. The difference between actual cash value and replacement cost coverage can be the difference between a new roof and a check that barely covers half of one. The terms sound technical, but the idea is simple.'),
      h2('Replacement cost value (RCV)'),
      p('Replacement cost pays what it actually costs to replace your damaged roof with a new one of similar kind and quality, minus your deductible. Age and wear do not reduce the payout. If a comparable new roof costs $15,000 and your deductible is $2,000, you can recover up to $13,000.'),
      h2('Actual cash value (ACV)'),
      p('Actual cash value pays the depreciated value: replacement cost minus depreciation for the age and condition of the old roof. If that same roof would cost $15,000 to replace but had lost $5,000 of value to age, the ACV is $10,000, and after your $2,000 deductible you receive $8,000. The older the roof, the bigger the bite.'),
      callout('warning', 'ACV policies are cheaper for a reason', 'Actual cash value coverage often runs 15 to 25 percent less in premium, but it can leave you paying thousands out of pocket after a loss. The savings disappear the first time you file a major claim.'),
      h2('Recoverable depreciation: the part people miss'),
      p('Here is the twist that confuses homeowners. With a replacement cost policy, the insurer often pays the ACV first and holds back the depreciation. That held-back amount is called recoverable depreciation, and you get it once the work is finished and you submit the final invoice proving you actually replaced the roof. You do not lose that money; you just have to do the repair to claim it.'),
      ...numbered([
        'Insurer pays ACV up front (replacement cost minus depreciation minus deductible)',
        'You hire a roofer and complete the replacement',
        'You submit the final invoice',
        'Insurer releases the recoverable depreciation',
      ]),
      h2('Watch for an ACV roof endorsement'),
      lp([
        'Even on a replacement cost home policy, insurers increasingly put older roofs on a separate ACV schedule. Read your declarations page, and if your roof is aging, see ',
        {text: 'how long a roof actually lasts', post: 'how-long-does-a-roof-last-in-texas'},
        ' to understand where yours stands.',
      ]),
      pullQuote('Replacement cost buys you a new roof. Actual cash value buys you a check for an old one. Know which you have before the storm, not after.'),
      cta('Find out what your roof is worth'),
    ],
  },
  {
    slug: 'what-roof-damage-is-not-covered-by-insurance',
    title: 'What Roof Damage Is NOT Covered by Homeowners Insurance',
    eyebrow: 'INSURANCE',
    excerpt:
      'Insurance covers sudden accidents, not slow decline. Here are the roof problems your policy will almost always refuse to pay for.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 6,
    daysAgo: 28,
    related: ['does-homeowners-insurance-cover-hail-damage', 'will-insurance-drop-me-for-roof-claim', 'roof-repair-vs-replacement'],
    body: [
      p('Homeowners insurance is built to cover sudden, accidental events, not the slow wearing-out of a roof over time. Understanding what falls outside that line saves you from filing claims that get denied and from assuming you are covered when you are not.'),
      h2('Wear, age, and neglect'),
      p('This is the big one. A roof that simply got old, lost its granules, and started leaking is considered a maintenance issue, not a covered loss. Insurers expect you to maintain and eventually replace your roof on your own dime. If an adjuster decides the damage came from age or neglect rather than a specific storm, the claim is denied.'),
      callout('tip', 'Maintenance is your best defense', 'Keeping records of inspections and minor repairs proves your roof was cared for, which makes it much harder for an insurer to blame storm damage on neglect.'),
      h2('Common exclusions and limits'),
      ...bullets([
        'Gradual leaks, rot, and water damage that built up over time',
        'Damage from lack of maintenance or unrepaired earlier problems',
        'Pest, insect, or animal damage',
        'Mold, in many policies, especially if it grew from an unaddressed leak',
        'Cosmetic-only damage, under some policies that exclude it',
        'Earthquakes and floods, which require separate coverage',
      ]),
      h2('The roof-age trap'),
      p('Older roofs face extra hurdles. Some insurers refuse to write replacement cost coverage on roofs past a certain age, switch them to actual cash value, or decline to renew. So even covered storm damage can pay far less than you expect on an older roof.'),
      h2('Separate deductibles for wind and hail'),
      p('In storm-prone areas, wind and hail damage is covered but carries a separate percentage deductible that can run into thousands. The damage is not excluded, but a large slice comes out of your pocket first.'),
      pullQuote('Insurance pays for the storm that hit your roof, not for the years that wore it down. Knowing the difference keeps your expectations honest.'),
      lp([
        'If your damage falls into a gray area, an honest professional inspection helps you tell genuine storm damage from age, and ',
        {text: 'decide whether to repair or replace', post: 'roof-repair-vs-replacement'},
        '.',
      ]),
      cta('Get an honest roof assessment'),
    ],
  },
  {
    slug: 'how-to-deal-with-roof-insurance-adjuster',
    title: 'How to Deal With an Insurance Adjuster for Roof Damage',
    eyebrow: 'INSURANCE',
    excerpt:
      'The adjuster works for the insurer, not for you. Here is how to be polite, prepared, and impossible to lowball.',
    category: 'category-insurance-claims',
    cover: INSURANCE,
    readTime: 7,
    daysAgo: 33,
    related: ['how-to-document-roof-damage-for-insurance', 'how-to-file-a-roof-insurance-claim', 'actual-cash-value-vs-replacement-cost-roof'],
    body: [
      p('The insurance adjuster is not your enemy, but they are not on your side either. Their job is to assess the damage and protect the insurer\'s money. Your job is to make sure nothing legitimate gets missed. That balance is won with preparation, not arguments.'),
      h2('Before the adjuster arrives'),
      ...bullets([
        'Have your full documentation organized: photos, video, and weather records',
        'Get an independent written estimate from a licensed roofer first',
        'Read your policy so you know your coverage and deductible',
        'Make a list of every area of damage so nothing is overlooked',
      ]),
      callout('tip', 'Have your roofer there', 'The single most effective move is to schedule your trusted contractor to be present during the inspection. They speak the same language as the adjuster and make sure damage on the roof itself is actually counted.'),
      h2('During the inspection'),
      p('Be cooperative and professional. Walk them through your documentation, point out every area of concern, and take your own notes on what they inspect and say. Do not exaggerate, and do not minimize. Let the evidence speak. If they seem to rush or skip areas, politely ask them to look again.'),
      h2('After you get the estimate'),
      lp([
        'Compare the adjuster\'s estimate line by line against your contractor\'s. Look for missing items, like flashing, underlayment, code-required upgrades, or disposal. Understand whether the offer is actual cash value or replacement cost, using ',
        {text: 'this breakdown', post: 'actual-cash-value-vs-replacement-cost-roof'},
        '.',
      ]),
      h2('If you disagree'),
      ...numbered([
        'Put your dispute in writing, with your contractor\'s estimate attached',
        'Ask for a re-inspection if damage was missed',
        'Request the specific policy language behind any denial',
        'Escalate to a supervisor, and know your policy may allow an appraisal process',
      ]),
      pullQuote('You do not beat an adjuster by being loud. You beat a lowball estimate by having better documentation than they do.'),
      h2('Keep it all in writing'),
      p('Summarize phone calls in a follow-up email, save every document, and log every conversation. A clear paper trail is what protects you if the claim turns into a dispute.'),
      cta('Get an estimate to match the adjuster'),
    ],
  },

  // ===================== REPAIR VS REPLACE =====================
  {
    slug: 'roof-repair-vs-replacement',
    title: 'How to Know if Your Roof Needs Repair or Full Replacement',
    eyebrow: 'DECIDE',
    excerpt:
      'A repair fixes a problem; a replacement resets the clock. Here is how to tell which one your roof actually needs, and avoid paying for the wrong one.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 8,
    daysAgo: 3,
    related: ['repair-or-replace-an-old-roof', 'how-long-does-a-roof-last-in-texas', 'roof-replacement-cost-texas'],
    body: [
      p('This is the question behind almost every roofing decision, and getting it wrong is expensive either way. Repair when you needed a replacement and you throw good money after bad. Replace when a repair would have done and you spend thousands you did not need to. Here is how to tell them apart.'),
      h2('When a repair is the right call'),
      p('Repairs make sense when the damage is localized, the rest of the roof is in good shape, and the roof has plenty of life left. A few missing shingles after a storm, a single leak around a vent, or damaged flashing are classic repair jobs.'),
      ...bullets([
        'Damage covers a small, contained area',
        'The roof is well within its expected lifespan',
        'A single leak with an obvious, fixable source',
        'Storm damage limited to one slope or section',
      ]),
      h2('When replacement is smarter'),
      p('Replacement wins when the damage is widespread, the roof is near the end of its life, or you find yourself repairing it again and again. At some point, patching an old roof is just delaying the inevitable at a premium.'),
      ...bullets([
        'Widespread damage across multiple slopes',
        'The roof is near or past its expected lifespan',
        'Repeated leaks in different spots',
        'Sagging, rot, or daylight visible through the deck',
        'Bald shingles with granules piling up in the gutters',
      ]),
      callout('info', 'The 30 percent guideline', 'A common rule of thumb among roofers: if damage affects more than about 30 percent of the roof, replacement is usually the better value than piecemeal repairs. Treat it as a starting point, not a hard law.'),
      h2('Run the simple cost math'),
      lp([
        'Compare the repair cost against the replacement cost spread over each roof\'s remaining years. A $1,500 repair on a roof with two years left is far worse value than the same repair on a roof with fifteen years left. Knowing ',
        {text: 'what a replacement actually costs', post: 'roof-replacement-cost-texas'},
        ' and ',
        {text: 'how long a roof lasts', post: 'how-long-does-a-roof-last-in-texas'},
        ' makes this call obvious.',
      ]),
      h2('Do not forget insurance and age'),
      lp([
        'If a storm caused the damage, your decision may be partly covered. And if your roof is old, see ',
        {text: 'whether it is worth repairing an old roof at all', post: 'repair-or-replace-an-old-roof'},
        '.',
      ]),
      pullQuote('A repair buys you time. A replacement buys you decades. The right choice is whichever costs less per year you actually get out of it.'),
      cta('Get a repair-or-replace assessment'),
    ],
  },
  {
    slug: 'roof-replacement-cost-texas',
    title: 'Average Cost of a Roof Replacement in Texas (2026)',
    eyebrow: 'COSTS',
    excerpt:
      'Most Texas roof replacements land between $7,500 and $25,000. Here is what drives the number and how to compare quotes fairly.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 8,
    featured: true,
    daysAgo: 8,
    related: ['roof-replacement-cost-florida', 'roof-repair-vs-replacement', 'how-long-does-a-roof-last-in-texas'],
    body: [
      p('A new roof is one of the biggest single repairs a Texas homeowner will pay for, and the price range is wide enough to be confusing. Let us put real 2026 numbers on it and explain what you are actually paying for, so you can read a quote with confidence.'),
      h2('The typical range in Texas'),
      p('For a standard single-family home, most Texas roof replacements fall between roughly $7,500 and $15,000 for asphalt shingles, with larger homes, premium materials, or complex roofs pushing past $25,000. The biggest single variable is the size of your roof.'),
      h2('Cost per square foot, by shingle type'),
      ...bullets([
        '3-tab asphalt shingles: roughly $3.50 to $5.50 per square foot installed',
        'Architectural (dimensional) shingles: roughly $5 to $9.50 per square foot installed',
        'Metal and tile: higher still, often double the cost of asphalt or more',
      ]),
      callout('info', 'Roofers price in "squares"', 'A roofing square is 100 square feet. A typical home might have 20 to 30 squares. When you compare quotes, make sure they are measuring the same number of squares and the same material.'),
      h2('What drives your price up or down'),
      ...bullets([
        'Roof size, measured in squares',
        'Material, from budget 3-tab to architectural, metal, or tile',
        'Pitch and complexity: steep, cut-up roofs cost more to work on safely',
        'Tear-off: removing old layers adds roughly $1 to $3 per square foot',
        'Your city, since labor in Houston, Dallas, and Austin runs higher than rural areas',
      ]),
      h2('Why two quotes can differ by thousands'),
      p('A higher quote is not automatically a rip-off. Contractors quote different materials, warranties, underlayment, and scopes of work. One may include tear-off, new flashing, and code upgrades while another quietly leaves them out. Always compare like for like, line by line.'),
      pullQuote('The cheapest quote is rarely the cheapest roof. Ask what is included and what happens in year eight, not just what you pay on day one.'),
      h2('Ways to manage the cost'),
      ...bullets([
        'Get at least three detailed, itemized quotes',
        'Ask about financing, which many contractors offer',
        'Time non-emergency work for the slower season',
        'If a storm caused the damage, check whether insurance covers part of it',
      ]),
      lp([
        'Before you commit, make sure replacement is even the right move with ',
        {text: 'our repair-or-replace guide', post: 'roof-repair-vs-replacement'},
        ', and only hire a roofer you have ',
        {text: 'properly vetted', post: 'find-licensed-roofing-contractor-texas'},
        '.',
      ]),
      cta('Compare quotes from vetted Texas roofers'),
    ],
  },
  {
    slug: 'roof-replacement-cost-florida',
    title: 'Average Cost of a Roof Replacement in Florida (2026)',
    eyebrow: 'COSTS',
    excerpt:
      'Florida roofs cost more for a reason: the building code is built for hurricanes. Here are 2026 prices and what the code adds.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 8,
    daysAgo: 13,
    related: ['roof-replacement-cost-texas', 'how-long-does-a-roof-last-in-florida', 'find-licensed-roofing-contractor-florida'],
    body: [
      p('Florida homeowners often pay more for a roof than people in other states, and it is not just demand. Florida has some of the strictest roofing requirements in the country, because the roof is your home\'s first line of defense against hurricane-force wind. Here is what a replacement really costs in 2026 and why.'),
      h2('The typical range in Florida'),
      p('Most Florida homeowners spend between roughly $10,000 and $20,000 for a full asphalt shingle replacement, with larger homes, tile, or metal pushing well past $30,000. Material choice is a huge factor here, because tile is so common in Florida.'),
      ...bullets([
        'Architectural asphalt shingles: roughly $5 to $9 per square foot',
        'Concrete or clay tile: roughly $12 to $21 per square foot, often $24,000 to $42,000 installed',
        'Standing seam metal: roughly $10 to $23 per square foot, often $20,000 to $46,000 installed',
      ]),
      h2('Why the building code adds cost'),
      lp([
        'Florida\'s building code requires features designed to survive hurricanes, and they add to the price. Expect sealed roof decks to limit water intrusion if the covering blows off, and enhanced roof-to-wall connections for uplift resistance. These are not upsells; they are required, and a quote that skips them is a red flag worth checking against our ',
        {text: 'list of contractor red flags', post: 'red-flags-when-hiring-a-roofing-contractor'},
        '.',
      ]),
      callout('tip', 'A wind mitigation inspection can pay you back', 'Florida insurers must offer premium credits for homes that meet windstorm standards. Features like hurricane straps, a sealed deck, and impact-rated materials can cut premiums by anywhere from 10 to 45 percent. The inspection often pays for itself.'),
      h2('The 25 percent rule, updated'),
      p('Florida\'s old "25 percent rule" once forced a full roof replacement if more than a quarter of the roof was damaged or repaired within a year. A 2022 law (SB 4-D) revised this. Now, if your roof was built or replaced to the 2007 Florida Building Code or later (broadly, roofs built or replaced after about March 1, 2009), you can repair just the damaged section instead of replacing the whole thing. Older roofs may still trigger the full-replacement requirement.'),
      pullQuote('In Florida you are not just buying shingles. You are buying a system engineered to keep its grip in a hurricane, and that engineering costs money.'),
      lp([
        'Florida also requires a state-licensed roofer for the work, so before you sign, read ',
        {text: 'how to find a licensed roofing contractor in Florida', post: 'find-licensed-roofing-contractor-florida'},
        '.',
      ]),
      cta('Compare quotes from licensed Florida roofers'),
    ],
  },
  {
    slug: 'how-long-does-a-roof-last-in-texas',
    title: 'How Long a Roof Lasts in Texas Heat',
    eyebrow: 'LIFESPAN',
    excerpt:
      'Texas sun is hard on roofs. Here is how long each material really lasts in the heat, and how to squeeze more years out of yours.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 6,
    daysAgo: 18,
    related: ['how-long-does-a-roof-last-in-florida', 'roof-replacement-cost-texas', 'repair-or-replace-an-old-roof'],
    body: [
      p('Roofs do not wear out on a fixed schedule. They wear out based on what they are made of and what the weather throws at them, and Texas throws a lot: relentless UV, triple-digit heat, sudden temperature swings, and hail. All of that shortens the life you would get in a milder climate.'),
      h2('Typical lifespans, and what Texas does to them'),
      ...bullets([
        'Asphalt shingles: 20 to 30 years nationally, often closer to the lower end in Texas heat',
        'Metal: 30 to 50 years or more, and it handles heat and sun very well',
        'Clay or concrete tile: 50 years and up, excellent in hot, dry conditions',
      ]),
      h2('Why heat ages a roof faster'),
      p('Intense UV and heat dry out the asphalt in shingles, making them brittle, curling the edges, and loosening the granules that protect them. Big daily temperature swings expand and contract the materials, working sealant and fasteners loose over time. A south or west-facing slope, which bakes the longest, usually ages first.'),
      callout('tip', 'Color and ventilation buy you years', 'Lighter-colored shingles reflect more sun and can last meaningfully longer in heat. And good attic ventilation lets trapped heat escape instead of cooking your roof from below, which is one of the cheapest ways to extend its life.'),
      h2('How to get the most out of your roof'),
      ...bullets([
        'Keep the attic well ventilated to release trapped heat',
        'Choose lighter, heat-reflective materials when you replace',
        'Inspect after every major hail or wind event',
        'Fix small problems early before the heat widens them',
      ]),
      pullQuote('In Texas, the sun is the slow vandal. It does not break your roof in a day; it wears it down a summer at a time.'),
      lp([
        'If your roof is getting up there in years, the next question is ',
        {text: 'whether to keep repairing it or replace it', post: 'repair-or-replace-an-old-roof'},
        '.',
      ]),
      cta('Get a roof age and condition check'),
    ],
  },
  {
    slug: 'how-long-does-a-roof-last-in-florida',
    title: 'How Long a Roof Lasts in Florida Humidity and Hurricanes',
    eyebrow: 'LIFESPAN',
    excerpt:
      'Heat, humidity, salt air, and hurricanes all gang up on Florida roofs. Here is what each material can really withstand, and for how long.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 6,
    daysAgo: 23,
    related: ['how-long-does-a-roof-last-in-texas', 'roof-replacement-cost-florida', 'what-storm-damage-to-a-roof-looks-like'],
    body: [
      p('Florida is one of the toughest places in the country to own a roof. It is not just the hurricanes. The everyday combination of heat, heavy humidity, salt air near the coast, and biological growth wears roofs down faster than a calmer climate would. Here is how long you can realistically expect a Florida roof to last.'),
      h2('Typical lifespans in Florida conditions'),
      ...bullets([
        'Asphalt shingles: 20 to 30 years in theory, often shorter in Florida heat and humidity',
        'Metal: 30 to 50 years or more, and a strong performer against wind',
        'Tile (clay or concrete): 50 years and up, which is why it is so popular in Florida',
      ]),
      h2('The four forces working against you'),
      ...numbered([
        'Heat and UV dry out and crack shingles, just as in other hot states',
        'Humidity feeds algae, moss, and mold that hold moisture against the surface and cause rot',
        'Salt air near the coast corrodes metal fasteners and components',
        'Hurricanes deliver sudden, violent damage that can end a roof\'s life in a single afternoon',
      ]),
      callout('info', 'Humidity is the quiet one', 'Those dark streaks on Florida roofs are usually algae. Beyond looking bad, the growth traps moisture against the shingles and slowly degrades them, which is why humid climates are so hard on roofs.'),
      h2('Wind ratings matter as much as lifespan'),
      lp([
        'In Florida, how well a roof survives a storm matters as much as how many years it lasts. The state building code requires hurricane-resistant features, which is part of why a ',
        {text: 'Florida roof replacement costs more', post: 'roof-replacement-cost-florida'},
        '. Those features also help your roof reach its full lifespan instead of being cut short by the next storm.',
      ]),
      h2('Stretching a Florida roof\'s life'),
      ...bullets([
        'Have algae and growth cleaned by a pro, not blasted off with a pressure washer',
        'Keep the attic ventilated to manage heat and moisture',
        'Inspect after every named storm',
        'Address small leaks immediately, before humidity turns them into rot',
      ]),
      pullQuote('A Florida roof does not just have to last. It has to survive. Lifespan and wind resistance are two different tests, and both matter.'),
      cta('Get a Florida roof inspection'),
    ],
  },
  {
    slug: 'repair-or-replace-an-old-roof',
    title: 'Is It Worth Repairing an Old Roof, or Should You Replace It?',
    eyebrow: 'DECIDE',
    excerpt:
      'Pouring money into an old roof can feel responsible and still be a mistake. Here is how to know when repairs stop making sense.',
    category: 'category-repair-vs-replace',
    cover: REPAIR,
    readTime: 7,
    daysAgo: 29,
    related: ['roof-repair-vs-replacement', 'how-long-does-a-roof-last-in-texas', 'roof-replacement-cost-texas'],
    body: [
      p('There is a moment with every aging roof where another repair stops being thrift and starts being denial. The hard part is recognizing it, because each individual repair feels cheaper than a full replacement, right up until you have spent more on patches than a new roof would have cost. Here is how to make the call clearly.'),
      h2('Do the cost-per-year math'),
      lp([
        'The honest way to compare is cost per year of life you actually get. A $2,000 repair on a roof with one or two years left costs you $1,000 to $2,000 per year. A $12,000 replacement that lasts 25 years costs under $500 per year. Once repairs cost more per year than replacement would, the math has flipped. You will need rough ',
        {text: 'replacement cost numbers', post: 'roof-replacement-cost-texas'},
        ' and a realistic sense of ',
        {text: 'how many years your roof has left', post: 'how-long-does-a-roof-last-in-texas'},
        '.',
      ]),
      h2('Signs an old roof is past repair'),
      ...bullets([
        'It is at or past its expected lifespan',
        'You are fixing new leaks every season, in different spots',
        'Shingles are widely curled, cracked, or bald of granules',
        'The deck sags, or you see daylight or rot from the attic',
        'A repair would visibly mismatch the worn, faded rest of the roof',
      ]),
      callout('tip', 'Repairs near the end have hidden costs', 'On a brittle old roof, even good repairs are hard to do cleanly, new materials rarely match, and the surrounding shingles may fail soon after. You can end up paying for a repair that buys only months.'),
      h2('When repair still makes sense on an older roof'),
      p('If the roof is aging but the damage is genuinely isolated, the rest is sound, and you have a real reason to wait, like selling soon or budgeting for next year, a targeted repair can be reasonable. The key is that it is a deliberate bridge, not a habit.'),
      h2('Factor in insurance and resale'),
      lp([
        'If a storm damaged an older roof, insurance may cover part of a replacement, though older roofs often pay out at depreciated value. Understand that in ',
        {text: 'actual cash value vs replacement cost', post: 'actual-cash-value-vs-replacement-cost-roof'},
        '. A new roof also helps at resale and can lower your insurance.',
      ]),
      pullQuote('Repairs that keep an old roof limping along are not saving you money. They are spreading the cost of a replacement out, with interest.'),
      cta('Get an honest old-roof assessment'),
    ],
  },

  // ===================== HIRING A PRO =====================
  {
    slug: 'find-licensed-roofing-contractor-texas',
    title: 'How to Find a Licensed Roofing Contractor in Texas',
    eyebrow: 'HIRING',
    excerpt:
      'Texas does not license roofers at the state level, which surprises most homeowners. Here is how to vet a Texas roofer the right way.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 7,
    daysAgo: 5,
    related: ['how-to-verify-roofer-licensed-and-insured', 'questions-to-ask-a-roofer-before-hiring', 'red-flags-when-hiring-a-roofing-contractor'],
    body: [
      p('Here is something most Texas homeowners do not know: Texas does not require a state license to be a roofing contractor. The state does not issue or regulate roofing licenses, which means anyone can legally call themselves a roofer. That puts the burden of vetting squarely on you, so here is how to do it properly.'),
      callout('warning', 'There is no statewide Texas roofing license', 'Because the state does not license roofers, "licensed" can mean very little in Texas on its own. Do not take the word at face value. Verify the things that actually protect you, listed below.'),
      h2('Look for voluntary certification'),
      p('While the state does not license roofers, the Roofing Contractors Association of Texas (RCAT) runs a voluntary certification program. RCAT-certified roofers have passed exams, carry insurance, and meet experience and bonding requirements. It is not legally required, but it is a strong, real signal of professionalism in a state with no mandatory license.'),
      h2('Check for local city requirements'),
      lp([
        'Some Texas cities, including San Antonio and Austin, do require roofers to register locally. Always confirm what your specific city requires, and that your contractor meets it. Pulling proper permits is part of this, and we cover verification in detail in ',
        {text: 'how to verify a roofer is licensed and insured', post: 'how-to-verify-roofer-licensed-and-insured'},
        '.',
      ]),
      h2('What actually protects you in Texas'),
      ...bullets([
        'Proof of general liability insurance, with the certificate sent directly from the insurer',
        'Workers compensation coverage for the crew',
        'RCAT certification or another credible credential',
        'A permanent local business address and a long local track record',
        'Strong, verifiable reviews and recent local references you can call',
      ]),
      h2('Watch out for storm chasers'),
      lp([
        'Texas storms attract out-of-state crews who knock on doors, pressure you to sign, and disappear when something goes wrong. The lack of a state license makes this easier for them. Learn the warning signs in ',
        {text: 'red flags when hiring a roofing contractor', post: 'red-flags-when-hiring-a-roofing-contractor'},
        '.',
      ]),
      pullQuote('In Texas, "licensed roofer" is not a meaningful claim by itself. Insurance, certification, and a real local track record are what protect you.'),
      lp([
        'Once you have a shortlist, put them through ',
        {text: 'the right questions before hiring', post: 'questions-to-ask-a-roofer-before-hiring'},
        '.',
      ]),
      cta('Find a vetted Texas roofer'),
    ],
  },
  {
    slug: 'find-licensed-roofing-contractor-florida',
    title: 'How to Find a Licensed Roofing Contractor in Florida',
    eyebrow: 'HIRING',
    excerpt:
      'Florida law requires a state license to do roofing work. Here is how to find one and verify it for free in two minutes.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 7,
    daysAgo: 11,
    related: ['how-to-verify-roofer-licensed-and-insured', 'roof-replacement-cost-florida', 'questions-to-ask-a-roofer-before-hiring'],
    body: [
      p('Florida takes roofing licenses seriously, and so should you. Unlike some states, Florida legally requires a roofing contractor to hold a valid state license before doing any roofing work. That is good news, because it gives you an official, free way to check whether the person quoting your roof is legitimate.'),
      h2('Who regulates Florida roofers'),
      p('Roofing licenses in Florida are issued and enforced by the Department of Business and Professional Regulation (DBPR) through its Construction Industry Licensing Board (CILB). A roofer working without one is breaking the law, and hiring one leaves you exposed if anything goes wrong.'),
      h2('Certified vs registered'),
      ...bullets([
        'Certified contractors can work anywhere in Florida. Their license number usually starts with the letters CCC.',
        'Registered contractors are limited to the specific local jurisdiction that issued their license.',
      ]),
      h2('How to verify a license for free'),
      lp([
        'Florida\'s official verification portal is MyFloridaLicense.com. Search by the contractor\'s name or license number, then check that the status reads "Current, Active." Anything else, like Delinquent, Suspended, Revoked, or Expired, means they cannot legally do your roof. We walk through this step by step in ',
        {text: 'how to verify a roofer is licensed and insured', post: 'how-to-verify-roofer-licensed-and-insured'},
        '.',
      ]),
      callout('tip', 'Confirm the license matches the person', 'Make sure the license belongs to the actual company quoting you, not a name they "borrowed." The qualifier on the license should match the business you are hiring.'),
      h2('Insurance still matters'),
      p('A license is the starting point, not the finish line. Florida roofers must also carry insurance, generally at least $100,000 in public liability and $25,000 in property damage coverage. Always get the insurance certificate sent directly from their insurer, not a copy they hand you.'),
      pullQuote('In Florida the license is non-negotiable and free to verify. If a roofer cannot give you a number that comes up active, the conversation is over.'),
      lp([
        'With the license confirmed, run your candidates through ',
        {text: 'the questions every roofer should be able to answer', post: 'questions-to-ask-a-roofer-before-hiring'},
        '.',
      ]),
      cta('Find a licensed Florida roofer'),
    ],
  },
  {
    slug: 'questions-to-ask-a-roofer-before-hiring',
    title: 'Questions to Ask a Roofer Before You Hire Them',
    eyebrow: 'HIRING',
    excerpt:
      'A great roofer answers these without hesitation. A bad one dodges. Use this list to separate the pros from the pretenders.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 6,
    daysAgo: 16,
    related: ['red-flags-when-hiring-a-roofing-contractor', 'how-to-verify-roofer-licensed-and-insured', 'never-pay-a-roofer-in-full-upfront'],
    body: [
      p('Hiring a roofer is a leap of faith. Most of the work happens out of sight, and you will not know if corners were cut until the next storm. The right questions, asked up front, are how you protect yourself before any money changes hands. A good contractor welcomes them.'),
      h2('Credentials and protection'),
      ...numbered([
        'Are you licensed where required, and fully insured? Can I see the documents?',
        'Do you carry general liability and workers compensation for your crew?',
        'Are you local, and how long have you worked in this area?',
        'Will you pull the required permits for this job?',
      ]),
      callout('warning', 'No insurance, no deal', 'If a contractor does not carry liability and workers compensation, an injury or accident on your property can become your financial problem. This one is non-negotiable, regardless of your state.'),
      h2('The work itself'),
      ...numbered([
        'Will you tear off the old roof, or install over it? (Tear-off is usually the right answer.)',
        'What underlayment, flashing, and ventilation will you use?',
        'Is the crew your own employees or subcontractors?',
        'How do you protect my landscaping and clean up nails afterward?',
      ]),
      h2('Money and warranty'),
      ...numbered([
        'Is this a detailed, written, itemized quote, not just a single number?',
        'What is the payment schedule?',
        'What workmanship warranty do you offer, in writing, and how long is it?',
        'What is your manufacturer warranty on the materials?',
      ]),
      lp([
        'Pay close attention to the payment answer. A reasonable deposit is normal, but a demand for full payment up front is a serious warning sign we explain in ',
        {text: 'why you should never pay a roofer in full upfront', post: 'never-pay-a-roofer-in-full-upfront'},
        '.',
      ]),
      pullQuote('You are not just buying shingles. You are buying the crew that installs them and their willingness to come back if something is wrong.'),
      lp([
        'If a roofer gets cagey on any of these, compare their behavior against our ',
        {text: 'list of red flags', post: 'red-flags-when-hiring-a-roofing-contractor'},
        '.',
      ]),
      cta('Get matched with roofers who answer straight'),
    ],
  },
  {
    slug: 'red-flags-when-hiring-a-roofing-contractor',
    title: 'Red Flags to Watch For When Hiring a Roofing Contractor',
    eyebrow: 'HIRING',
    excerpt:
      'The worst roofing experiences almost always show warning signs early. Here are the red flags that should make you walk away.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 7,
    daysAgo: 21,
    related: ['questions-to-ask-a-roofer-before-hiring', 'never-pay-a-roofer-in-full-upfront', 'how-to-verify-roofer-licensed-and-insured'],
    body: [
      p('Most roofing horror stories were avoidable. The warning signs were there at the start, but they were easy to miss under pressure, especially right after a storm. Learn to spot these red flags and you will dodge the vast majority of bad contractors before they ever touch your roof.'),
      h2('The door-knocking storm chaser'),
      p('Right after a big storm, crews flood damaged neighborhoods offering instant deals. Some are fine, but many are out-of-town operations that collect a deposit, do shoddy or no work, and vanish before the problems surface. Be especially wary of anyone who shows up uninvited and pressures you to decide on the spot.'),
      h2('Pressure and urgency tactics'),
      ...bullets([
        '"This price is only good if you sign today"',
        'Pushing you to commit before you have a written quote',
        'Discouraging you from getting other estimates',
        'Offering to "waive your deductible," which is often insurance fraud',
      ]),
      callout('warning', 'Waiving your deductible is a trap', 'A roofer who offers to eat your insurance deductible is usually inflating the claim or cutting corners to cover it. It is illegal in many states and a sign the whole deal is dishonest.'),
      h2('Money red flags'),
      lp([
        'Demanding full payment up front, asking for large cash-only deposits, or having no written contract are all serious warnings. A reasonable deposit is fine; paying for the whole job before it is done is not, as we explain in ',
        {text: 'never pay a roofer in full upfront', post: 'never-pay-a-roofer-in-full-upfront'},
        '.',
      ]),
      h2('Credibility red flags'),
      ...bullets([
        'No verifiable license where one is required, or no proof of insurance',
        'No permanent local address, only a cell phone',
        'No written estimate, or a vague one-line quote',
        'No references, or reviews that feel fake or thin',
        'Vague, evasive answers to direct questions',
      ]),
      pullQuote('A good roofer earns the job with patience and paperwork. A bad one rushes you past both. Pressure is the reddest flag of all.'),
      lp([
        'Counter every one of these by ',
        {text: 'verifying credentials yourself', post: 'how-to-verify-roofer-licensed-and-insured'},
        ' and ',
        {text: 'asking the right questions', post: 'questions-to-ask-a-roofer-before-hiring'},
        ' before you sign anything.',
      ]),
      cta('Find vetted, no-pressure roofers'),
    ],
  },
  {
    slug: 'how-to-verify-roofer-licensed-and-insured',
    title: 'How to Verify a Roofing Contractor Is Licensed and Insured',
    eyebrow: 'HIRING',
    excerpt:
      'Do not take "licensed and insured" on faith. Here is exactly how to confirm both yourself, in Texas and Florida, before you sign.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 7,
    daysAgo: 26,
    related: ['find-licensed-roofing-contractor-florida', 'find-licensed-roofing-contractor-texas', 'questions-to-ask-a-roofer-before-hiring'],
    body: [
      p('"Licensed and insured" is the most common phrase in roofing advertising, and one of the least verified by homeowners. It takes only a few minutes to confirm both, and skipping that step is how people end up liable for accidents or stuck with unlicensed work. Here is exactly how to check.'),
      h2('Verifying the license depends on your state'),
      lp([
        'Licensing rules vary, so start with what your state actually requires. In Florida, roofers must hold a state license, which you can verify free at MyFloridaLicense.com. In Texas, there is no state roofing license at all, so you verify other credentials instead. We cover each in ',
        {text: 'finding a licensed roofer in Florida', post: 'find-licensed-roofing-contractor-florida'},
        ' and ',
        {text: 'finding one in Texas', post: 'find-licensed-roofing-contractor-texas'},
        '.',
      ]),
      h2('How to check a Florida license'),
      ...numbered([
        'Go to the official DBPR portal at MyFloridaLicense.com',
        'Search by the company name or the license number from the quote',
        'Confirm the status reads "Current, Active"',
        'Check that the license holder matches the business quoting you',
      ]),
      h2('What to check in Texas'),
      p('Since Texas has no state license, verify RCAT certification if they claim it, confirm any local city registration your area requires, and lean harder on insurance and references. The absence of a license makes the next step, insurance, even more important.'),
      h2('Verifying insurance the right way'),
      lp([
        'This is the step almost everyone gets wrong. Do not accept a paper certificate the contractor hands you, because it can be expired or fake. Instead, ask for the insurance company\'s name and policy number, then call the insurer directly to confirm the policy is active and covers the work dates. You want both general liability and workers compensation. This protects you if a worker is hurt on your property, a risk highlighted in ',
        {text: 'questions to ask before hiring', post: 'questions-to-ask-a-roofer-before-hiring'},
        '.',
      ]),
      callout('tip', 'Get the certificate from the source', 'Ask the contractor to have their insurer send the certificate of insurance directly to you. A legitimate roofer does this without complaint.'),
      pullQuote('Verifying takes ten minutes. Not verifying can cost you a lawsuit, a failed inspection, or a roof you cannot insure.'),
      cta('Find pre-verified roofers'),
    ],
  },
  {
    slug: 'never-pay-a-roofer-in-full-upfront',
    title: 'Why You Should Never Pay a Roofer in Full Upfront',
    eyebrow: 'HIRING',
    excerpt:
      'A deposit is normal. Paying for the whole job before it starts hands away your only leverage. Here is how to structure payment safely.',
    category: 'category-hiring-a-pro',
    cover: HIRING,
    readTime: 6,
    daysAgo: 31,
    related: ['red-flags-when-hiring-a-roofing-contractor', 'questions-to-ask-a-roofer-before-hiring', 'how-to-verify-roofer-licensed-and-insured'],
    body: [
      p('Your payment schedule is the most powerful tool you have to make sure the work actually gets done, and done right. The moment you pay in full, that leverage is gone. A contractor who has already been paid has no financial reason to finish on time, fix mistakes, or come back at all. That is why full upfront payment is one of the clearest warning signs in the business.'),
      h2('Why a reasonable deposit is normal'),
      p('Asking for some money up front is standard and fair. Roofers buy materials and schedule crews before the job starts. A deposit in the range of 10 to 30 percent is typical and reasonable. The problem is not paying something; it is paying everything.'),
      callout('warning', 'Full payment upfront is a red flag', 'A contractor who demands the entire amount before starting, or wants a large cash-only deposit, is either struggling financially or planning to underdeliver. Either way, walk away.'),
      h2('A safe payment structure'),
      ...numbered([
        'A modest deposit to secure your spot and cover initial materials',
        'A progress payment partway through, tied to actual completed work',
        'The final, largest payment only after the job is finished and you have inspected it',
      ]),
      p('Tying payments to milestones keeps everyone honest and gives you room to pause if something is not right.'),
      h2('Protect yourself further'),
      ...bullets([
        'Get the full payment schedule in writing in the contract',
        'Pay by check or card, never large amounts of cash, so you have a record',
        'Hold the final payment until you have walked the finished roof',
        'Never let a payment outpace the work that has actually been done',
      ]),
      lp([
        'A demand for full upfront payment rarely travels alone. It usually comes with other warning signs, so review the full ',
        {text: 'list of contractor red flags', post: 'red-flags-when-hiring-a-roofing-contractor'},
        ' and make sure you have ',
        {text: 'verified their license and insurance', post: 'how-to-verify-roofer-licensed-and-insured'},
        ' before any money changes hands.',
      ]),
      pullQuote('Your final payment is your only real leverage. Never give it up before the work is done and inspected.'),
      cta('Find roofers with fair payment terms'),
    ],
  },
]

// ---------------------------------------------------------------------------
// Seed
// ---------------------------------------------------------------------------

function isoDaysAgo(days: number): string {
  const ms = Date.now() - days * 24 * 60 * 60 * 1000
  return new Date(ms).toISOString()
}

async function wipe() {
  // Delete posts first (they hold the references to authors/categories), then
  // the rest. relatedPosts references among posts are removed together.
  for (const type of ['post', 'category', 'author'] as const) {
    const ids = await client.fetch<string[]>('*[_type == $type]._id', {type})
    if (ids.length) {
      let tx = client.transaction()
      for (const id of ids) tx = tx.delete(id)
      await tx.commit()
    }
    console.log(`  wiped   ✓ ${ids.length} ${type}${ids.length === 1 ? '' : 's'}`)
  }
}

async function main() {
  console.log(`Seeding blog into ${projectId}/${dataset} (covers via ${OG_BASE})\n`)

  // 0. Wipe everything
  await wipe()

  // 1. Author (single brand byline)
  const logoId = await uploadLogo('logo/logo.png')
  await client.createOrReplace({
    _id: AUTHOR_ID,
    _type: 'author',
    name: 'Hommy',
    slug: {_type: 'slug', current: 'hommy'},
    role: 'Home Services Editorial Team',
    image: {_type: 'image', asset: {_type: 'reference', _ref: logoId}, alt: 'Hommy'},
  })
  console.log(`  author  ✓ Hommy`)

  // 2. Categories
  for (const cat of categories) {
    await client.createOrReplace({
      _id: cat._id,
      _type: 'category',
      title: cat.title,
      slug: {_type: 'slug', current: cat.slug},
      description: cat.description,
    })
    console.log(`  category ✓ ${cat.title}`)
  }

  // 3. Posts (generate cover, then create; relatedPosts patched in a 2nd pass)
  for (const post of posts) {
    const coverId = await uploadCover(post.slug, post.title, post.cover)
    await client.createOrReplace({
      _id: `post-${post.slug}`,
      _type: 'post',
      title: post.title,
      slug: {_type: 'slug', current: post.slug},
      eyebrow: post.eyebrow,
      excerpt: post.excerpt,
      mainImage: {_type: 'image', asset: {_type: 'reference', _ref: coverId}, alt: post.title},
      body: post.body,
      category: {_type: 'reference', _ref: post.category},
      author: {_type: 'reference', _ref: AUTHOR_ID},
      publishedAt: isoDaysAgo(post.daysAgo),
      readTime: post.readTime,
      featured: post.featured ?? false,
      seo: {
        metaTitle: post.title.slice(0, 60),
        metaDescription: post.excerpt.slice(0, 160),
        noIndex: false,
      },
    })
    console.log(`  post     ✓ ${post.title}`)
  }

  // 4. Related posts (second pass, all targets now exist)
  for (const post of posts) {
    if (!post.related?.length) continue
    await client
      .patch(`post-${post.slug}`)
      .set({
        relatedPosts: post.related.slice(0, 3).map((slug) => ({
          _type: 'reference',
          _key: key(),
          _ref: `post-${slug}`,
        })),
      })
      .commit()
  }

  console.log(`\nDone. 1 author, ${categories.length} categories, ${posts.length} posts.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
