/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Embed = {
  _type: "embed";
  url: string;
  caption?: string;
};

export type Cta = {
  _type: "cta";
  label: string;
  link: Link;
  variant?: "primary" | "secondary";
};

export type PullQuote = {
  _type: "pullQuote";
  quote: string;
  attribution?: string;
};

export type Callout = {
  _type: "callout";
  tone: "info" | "tip" | "warning" | "success";
  title?: string;
  content: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  asset: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  caption?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageBlock)
  | ({
      _key: string;
    } & Callout)
  | ({
      _key: string;
    } & PullQuote)
  | ({
      _key: string;
    } & Cta)
  | ({
      _key: string;
    } & Embed)
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Link = {
  _type: "link";
  linkType: "internal" | "external";
  internalLink?: PostReference | CategoryReference;
  href?: string;
  openInNewTab?: boolean;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  eyebrow?: string;
  excerpt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body?: BlockContent;
  category: CategoryReference;
  author: AuthorReference;
  publishedAt: string;
  readTime?: number;
  featured?: boolean;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Embed
  | Cta
  | PullQuote
  | Callout
  | SanityImageAssetReference
  | ImageBlock
  | BlockContent
  | PostReference
  | CategoryReference
  | Link
  | Seo
  | AuthorReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]    | order(featured desc, publishedAt desc) {      _id,  title,  "slug": slug.current,  eyebrow,  excerpt,  publishedAt,  readTime,  featured,  mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    category->{ _id, title, "slug": slug.current },    author->{    name,    "slug": slug.current,    role,    image {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }  }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  eyebrow: string | null;
  excerpt: string;
  publishedAt: string;
  readTime: number | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  author: {
    name: string;
    slug: string;
    role: string | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
}>;

// Source: ../src/sanity/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && defined(slug.current) && category->slug.current == $categorySlug]    | order(featured desc, publishedAt desc) {      _id,  title,  "slug": slug.current,  eyebrow,  excerpt,  publishedAt,  readTime,  featured,  mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    category->{ _id, title, "slug": slug.current },    author->{    name,    "slug": slug.current,    role,    image {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }  }  }
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  eyebrow: string | null;
  excerpt: string;
  publishedAt: string;
  readTime: number | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  author: {
    name: string;
    slug: string;
    role: string | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
}>;

// Source: ../src/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "postCount": count(*[_type == "post" && references(^._id) && defined(slug.current)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  postCount: number;
}>;

// Source: ../src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    eyebrow,    excerpt,    publishedAt,    _updatedAt,    readTime,    featured,    mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },      category->{ _id, title, "slug": slug.current },    author->{      name,      "slug": slug.current,      role,      image {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }    },    body[]{      ...,      _type == "imageBlock" => {        ...,        asset{          asset->{ _id, url, metadata { lqip, dimensions { width, height } } },          hotspot,          crop        }      },      markDefs[]{        ...,        _type == "link" => {          ...,          internalLink->{ _type, "slug": slug.current }        }      }    },    seo {      metaTitle,      metaDescription,      noIndex,      ogImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }    },    relatedPosts[]->{        _id,  title,  "slug": slug.current,  eyebrow,  excerpt,  publishedAt,  readTime,  featured,  mainImage {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop },    category->{ _id, title, "slug": slug.current },    author->{    name,    "slug": slug.current,    role,    image {   asset->{    _id,    url,    metadata { lqip, dimensions { width, height } }  },  alt,  hotspot,  crop }  }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  eyebrow: string | null;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  readTime: number | null;
  featured: boolean | null;
  mainImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
        } | null;
      } | null;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  author: {
    name: string;
    slug: string;
    role: string | null;
    image: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          _type: "link";
          linkType: "external" | "internal";
          internalLink:
            | {
                _type: "category";
                slug: string;
              }
            | {
                _type: "post";
                slug: string;
              }
            | null;
          href?: string;
          openInNewTab?: boolean;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone: "info" | "success" | "tip" | "warning";
        title?: string;
        content: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "cta";
        label: string;
        link: Link;
        variant?: "primary" | "secondary";
        markDefs: null;
      }
    | {
        _key: string;
        _type: "embed";
        url: string;
        caption?: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "imageBlock";
        asset: {
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
              } | null;
            } | null;
          } | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
        };
        alt: string;
        caption?: string;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "pullQuote";
        quote: string;
        attribution?: string;
        markDefs: null;
      }
  > | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    ogImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  } | null;
  relatedPosts: Array<{
    _id: string;
    title: string;
    slug: string;
    eyebrow: string | null;
    excerpt: string;
    publishedAt: string;
    readTime: number | null;
    featured: boolean | null;
    mainImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
          } | null;
        } | null;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    };
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    author: {
      name: string;
      slug: string;
      role: string | null;
      image: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
            } | null;
          } | null;
        } | null;
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    };
  }> | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(featured desc, publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  eyebrow,\n  excerpt,\n  publishedAt,\n  readTime,\n  featured,\n  mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n },\n  \n  category->{ _id, title, "slug": slug.current }\n,\n  \n  author->{\n    name,\n    "slug": slug.current,\n    role,\n    image { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n }\n  }\n\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && category->slug.current == $categorySlug]\n    | order(featured desc, publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  eyebrow,\n  excerpt,\n  publishedAt,\n  readTime,\n  featured,\n  mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n },\n  \n  category->{ _id, title, "slug": slug.current }\n,\n  \n  author->{\n    name,\n    "slug": slug.current,\n    role,\n    image { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n }\n  }\n\n\n  }\n': POSTS_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "postCount": count(*[_type == "post" && references(^._id) && defined(slug.current)])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    eyebrow,\n    excerpt,\n    publishedAt,\n    _updatedAt,\n    readTime,\n    featured,\n    mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n },\n    \n  category->{ _id, title, "slug": slug.current }\n,\n    author->{\n      name,\n      "slug": slug.current,\n      role,\n      image { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n }\n    },\n    body[]{\n      ...,\n      _type == "imageBlock" => {\n        ...,\n        asset{\n          asset->{ _id, url, metadata { lqip, dimensions { width, height } } },\n          hotspot,\n          crop\n        }\n      },\n      markDefs[]{\n        ...,\n        _type == "link" => {\n          ...,\n          internalLink->{ _type, "slug": slug.current }\n        }\n      }\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      noIndex,\n      ogImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n }\n    },\n    relatedPosts[]->{\n      \n  _id,\n  title,\n  "slug": slug.current,\n  eyebrow,\n  excerpt,\n  publishedAt,\n  readTime,\n  featured,\n  mainImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n },\n  \n  category->{ _id, title, "slug": slug.current }\n,\n  \n  author->{\n    name,\n    "slug": slug.current,\n    role,\n    image { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height } }\n  },\n  alt,\n  hotspot,\n  crop\n }\n  }\n\n\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
  }
}
